apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-token-secret
    namespace: cert-manager
data:
    api-token: ENC[AES256_GCM,data:Izu1qMdr/YDn93cor8iD3rLRurVUvMdrWjSAWmJVigY0rX5HPR9+Xesdzd4/ENe2P5LSpSF0SdE=,iv:z7LMY/G/yuvVbXQFtq/fCeJPIMeN3P9ldHPJjhbcn7w=,tag:Kde8iXwRQ2g1NwCH/l5aRQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1hlfnnwk9z9jynzngesd0j35n6rmpry70z9zak6ullmvesvvjge2sjc9nsf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwajFuRWZGekJTQlk3ZkVC
            MHc5b0RaQTd2b1hOenJ1U2VnTlNWRXBEb1hVCnhtNkhucXBDTy9QOUpCYWV1OFhi
            TU5lNTNiK0ZZN0NQT2luczlRMWJtTGMKLS0tIE1TN1NUb2crUE9XTTVNVlBlRUhk
            MFdjRnZaLy9lYWo1VlFDSHoxM2lIL3cK4MRkT0zSxDJws0+Z/UkRsSJ2uo4ix0sL
            Z+7h+CthCbLcOM7kjP8E5drFxCfg0B7PO2ISMyVJKBH2ZwK4U73wJg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-16T15:03:18Z"
    mac: ENC[AES256_GCM,data:9sCh6ZAbtsuL1ZcwXFNwRcLQYuP7reGRC5qSJdvl8QoVPylI7M5R5JHtbVoYZvZd5pT7AIrqF0lPoosPBQCYIIC3zFGAXideYca6VUWfoxIceBJ7o73OSuI7C74N42HMvmx6Z9E9pI1n1enbWlHUS85O7cIadJAnPPnALNCi3HE=,iv:C8CD7DQJsdErXv+SOpvXJKbvJN/b63xF2/nwJuiq0tA=,tag:NHJYQKaRTR09KQkOW8lzbg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
