apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
- helm-release.yaml
- cloudflare-api-token-secret.sops.yaml
- letsencrypt-production.yaml
- letsencrypt-staging.yaml
- service-monitor.yaml
- prometheus-rules.yaml
