---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: velero
  namespace: velero
spec:
  interval: 5m
  chart:
    spec:
      chart: velero
      version: 3.2.0
      sourceRef:
        kind: HelmRepository
        name: vmware-tanzu-charts
        namespace: flux-system
  values:
    initContainers:
      - name: velero-plugin-for-aws
        image: velero/velero-plugin-for-aws:v1.7.0
        imagePullPolicy: IfNotPresent
        volumeMounts:
          - mountPath: /target
            name: plugins
    upgradeCRDs: false
    configuration:
      provider: "aws"
      backupStorageLocation:
        name: scaleway
        bucket: test-bucket
        default: true
        config:
          region: nl-ams
          s3Url: https://s3.nl-ams.scw.cloud
      volumeSnapshotLocation:
        name: scaleway
        bucket: test-bucket
        default: true
        config:
          region: nl-ams
          s3Url: https://s3.nl-ams.scw.cloud
    credentials:
      existingSecret: scaleway-api-credentials-secret
