---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: velero
  namespace: velero
spec:
  interval: 5m
  chart:
    spec:
      chart: velero
      version: 5.1.4
      sourceRef:
        kind: HelmRepository
        name: vmware-tanzu-charts
        namespace: flux-system
  values:
    initContainers:
      - name: velero-plugin-for-aws
        image: velero/velero-plugin-for-aws:v1.8.2
        imagePullPolicy: IfNotPresent
        volumeMounts:
          - mountPath: /target
            name: plugins
    upgradeCRDs: false
    configuration:
      backupStorageLocation:
        - name: scaleway
          provider: "aws"
          bucket: test-bucket
          default: true
          config:
            region: nl-ams
            s3Url: https://s3.nl-ams.scw.cloud
      volumeSnapshotLocation:
        - name: scaleway
          provider: "aws"
          bucket: test-bucket
          default: true
          config:
            region: nl-ams
            s3Url: https://s3.nl-ams.scw.cloud
    credentials:
      existingSecret: scaleway-api-credentials-secret
