---
apiVersion: v1
data:
    age.agekey: ENC[AES256_GCM,data:twWzGduj3UFhAA90FeYhpWrZ4P0t0kRusED6Tsn4kqCpmlEncN93iQtahp771aL2jFWAvysZ8uUaBp3bwG2KefcKqOnQOcDfENJws9SByXwampuMbk/0s5T/T66VPVDyXv70WrHxProuRcCq6TALqjJMd/DxInvrk4BNlsVlFMdd8tZeu5lRI3K37aOBo29YmYYpVVlLyQXpwD0Cwpwd9dthl7KwkOTIfGmQb/lQG/2+0l9PlWjiZTbLGsfVRLXFuUNbouF8ruZGkwR9M52yoIeLeQZ8DQJwLFhoS/7SmLo4c1DnyyoYyJb2sf6CCHwRSxHyxlWrMBi78rl1,iv:0oAfyOjKdYirF5l8bcdKT0SOf2J3uaxAi5+B1Rs3gRA=,tag:luNk4eK0n7Qjc+293zA0QQ==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: sops-age
    namespace: flux-system
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1hlfnnwk9z9jynzngesd0j35n6rmpry70z9zak6ullmvesvvjge2sjc9nsf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtVVhOdUE3RVpOd0RZTnJp
            SW12aXBkVU4zbmpJUzBhSzdKajhDazA0QkFBCnBlUUN3S21jc1NwNFBEaEhhQUM3
            cjdWM3ZUSTBQOG42aWFpdG04ZjFVQ0kKLS0tIElhcTl6dGpKb21ZbUtNZDVBSEl0
            YU12YmZkbEZHc1J4SjU2ekU2UWwzYmsKcM+1BDKmj/YELLPG0tmu5CT91oQW6d/h
            Q/Oi5+Qgxlg9S/XaSj4cxc00pnXznSL7q+TMW7g8iQdIDHPeyhqrqg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-12-29T18:11:43Z"
    mac: ENC[AES256_GCM,data:nAZZb+lqkLFDmRTfucZsqFkD4ndUMcvJiSvTPDYNrSY0sp4tgGMOjfSJJ1+gcF+jdatRAHjIl5fbWPrQmhCB/iZyWFqdc/cHUcCZ+urHDv+/AIzMd6Ae4D+nxKuiwUiJLo8P2QpeOjDGMwlIPGjHPlsBqOtKNZCVapjXm5kEz4A=,iv:7JeyLONt2a6bUMZyd0GrrH0u6xGfsAjAxFYXucwT5Qs=,tag:a5MZK3NtM/wjC11vCMESNg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
