---
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
data:
    TRACCAR_DOMAIN: ENC[AES256_GCM,data:3BmusF11V9C5CcSBEWiTDHdyYBkKEx8aVaKYvA==,iv:N9HjN1S2to3ICbHEbqlqNz0bwxAiz3R5wydXIQP6NJY=,tag:69hgMaiZEDYgwx5SnLU89w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1hlfnnwk9z9jynzngesd0j35n6rmpry70z9zak6ullmvesvvjge2sjc9nsf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYYUJIeDJMQ2xwZ0wyN2h4
            bnQ5YXVOeFRMTEo5N2ptM2RXRW10YjlObGpJCmE3bTRjcXA1YWhYQ0RySW41VGlO
            Y0ZkeTd1dFRvR0VzQ2VLNlh4NTBUN28KLS0tIGdDWGRvUE1tK0MwZHFjTTRDNE81
            YUNFTU9qQXF0VXhjWkhuM21OdXBXT0kKMuSKR0KQoD5KQNdzqgEVBvysF5LL1ZaS
            1w9u5MF81hu4ZmCLCzoWy0bTUCJo+wwfH6yyBK31aCNhbnPLAUUiNg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-01-26T21:15:42Z"
    mac: ENC[AES256_GCM,data:0TNHnYx2dnCxjLmMxFTNr7/Nc588KfalfWfo49pL9jttvzHlShkX/0031Xf9OhxkH49D13/wIw419vLfgg6rnVLqPpYu8FRnDibFg0nnqa1poX16mABwlUej0KxuAKiCVkTpe8SwWRq0ZgbfmTfajcaf5I8m7axmzZrbc6ujThM=,iv:pJc1829afS/rmR+LkADw9eeavbK+aSL1nBtRT5akXZQ=,tag:nP6Cc3tfsJx1VNAs+r9ZNg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
