apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: www-to-non-www
  namespace: networking
spec:
  redirectRegex:
    regex: ^https://www.(.*)
    replacement: https://$1
    permanent: true
