apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: x-robots
  namespace: networking
spec:
  headers:
    customResponseHeaders:
      X-Robots-Tag: "noindex,nofollow,nosnippet,noarchive,notranslate,noimageindex"
