---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # renovate: datasource=docker image=rancher/system-upgrade-controller
  - https://github.com/rancher/system-upgrade-controller/releases/download/v0.11.0/crd.yaml
  - https://github.com/rancher/system-upgrade-controller?ref=v0.11.0
images:
- name: rancher/system-upgrade-controller
  newTag: v0.11.0
patchesStrategicMerge:
# Delete namespace resource
- |
  $patch: delete
  apiVersion: v1
  kind: Namespace
  metadata:
    name: system-upgrade
---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- server-plan.yaml
- agent-plan.yaml
