---
apiVersion: upgrade.cattle.io/v1
kind: Plan
metadata:
  name: k3s-server
  namespace: system-upgrade
spec:
  # renovate: datasource=github-releases depName=k3s-io/k3s
  version: v1.27.7+k3s2
  concurrency: 1
  serviceAccountName: system-upgrade
  nodeSelector:
    matchExpressions:
    - key: node-role.kubernetes.io/master
      operator: In
      values:
      - "true"
  cordon: true
  upgrade:
    image: rancher/k3s-upgrade
