apiVersion: v1
kind: Secret
metadata:
    name: postgresql-secrets
    namespace: selfhosted
data:
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:AcQ5y9YiQ4AlfWjN3KSwHq8NnVb/gXDCpAIgnA==,iv:odlOhtoyK4GLaf1bUsTaqXJpB+EYUqeBW6l8bI2gzZI=,tag:zOkQ/WoUR8gFjRLFzBIxwg==,type:str]
    POSTGRES_DB: ENC[AES256_GCM,data:xAhOMcZiqAzmCzlf,iv:bSm9PR2x72WBFgqHuL0nY417SIdLETWoGDtvi3To/Ok=,tag:dJdJ9XgvTZ0dG1SEZFM/1w==,type:str]
    USERDB_USER: ENC[AES256_GCM,data:TyqnMNeC+t+ke65N,iv:0vBflMcNEQ4QMEWCrEHxLSBnsZwFldnSxZIMgS7Ruk0=,tag:jsS42qk1HhIPM/L108MjaA==,type:str]
    USERDB_PASSWORD: ENC[AES256_GCM,data:TT2LewfFfle0JnEK,iv:9IR0OwFPc/fbA7OHe5j82CAQllYmMYEA1uuj4eb0hwI=,tag:AXBa5C9ZkzFZ+LdPamBs7A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1hlfnnwk9z9jynzngesd0j35n6rmpry70z9zak6ullmvesvvjge2sjc9nsf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3ZXl1VjdGOVhyQnlaaVpF
            WDlhKzFCaHFRWEF6YjY1aHVSVGlMTmhiUmdnCi9UdDhmMjNPZUl3OFdXR3daNlNV
            aGttVDl5WlpkMlU0T1oyZmVSS1FLUUUKLS0tIGlab1h5L2s1cTdGT2IwaFpQOG9W
            RkMvRGhjdm5INDlEdTkxNVFwQmZ3SlEK5RCV6e+ujhR3wcd74+P3ke0F/etppTKP
            O0lHV7E3HwgwV8HeJKqAeZ5dqs3Ikf/2BGDC2S6zFgafaWXyDjgY6g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-01-24T19:42:38Z"
    mac: ENC[AES256_GCM,data:bYbHv0DwDbxzCk1rUbh01i8kA00RxbDehFTOynU5Ypb8UAnlODD5M5mlCrbjTYEJlDu6JLPB+rGLWXW0RLvc6QrcwAzWnQ7VnSdNzy9AZGejGwR4eveAgymIakf/wjBNuo1H0sW2/AvMgyfO0ElonTFbHPJnnOVfwZmVs9KbZkQ=,iv:fVBE1SdSRnbZ0uxwECCJRgJi5D6dQVtYG7Wd6sLK6JQ=,tag:qEBXztrQU3Y36V+5fvhCMw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
