---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: traccar-postgresql
  namespace: selfhosted
spec:
  interval: 5m
  chart:
    spec:
      chart: postgres
      version: 0.4.4
      sourceRef:
        kind: HelmRepository
        name: groundhog2k-charts
        namespace: flux-system
      interval: 5m
  values:
    extraEnvSecrets:
      - postgresql-secrets
    customScripts:
      02-grant-public.sh: |
        psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" <<-EOSQL
          ALTER DATABASE traccar OWNER TO traccar;
        EOSQL
    storage:
      requestedSize: 5G
